services:
  postgres:
    image: postgres:16
    container_name: pf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practico_final
    ports:
      - "5432:5432"
    volumes:
      - pf-postgres-data:/var/lib/postgresql/data

volumes:
  pf-postgres-data:
